sudo: false
language: erlang
notifications:
  email:
    - ayanda.dube@erlang-solutions.com
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - awscli
      # Use Elixir from Erlang Solutions. The provided Elixir is
      # installed with kiex but is old. We also can't use kiex to
      # install a newer one because of GitHub API rate limiting.
      - elixir=1.4.5-1
cache:
  apt: true
otp_release:
  - "19.3"
  - "20.1"

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, v3.8.x branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream v3.8.x:v3.8.x || :
    git fetch upstream master:master || :
  # Make sure we use Elixir from Erlang Solutions and not kiex.
  - |
    echo YES | kiex implode
    elixir --version
    elixir --version | grep -q 'Elixir 1.4.5'

script:
  - make xref
  - make tests
